### ISSUE TITLE
Run Script?

### ISSUE THREAD

**Issue by ArtSabintsev** [fastred/IBAnalyzer#12]
Just a suggestion - anyway that this could be turned into a run script when you build or run your app? It'll throw a warning/error if it finds an issue. Alternatively, SwiftLint integration seems appropriate, since these types of issues are akin to their `force_try` rule, which throws an error if you implicitly unwrap any optionals.

Just my $0.02.

Thanks for your work!

**Comment by fastred** [comment]
Yes, this would be ideal. It's not implemented yet mostly because of two reasons:

- I would first like to eliminate all known false positives; alternatively add a way to opt out from showing warnings for some of the classes
- distribution through CocoaPods and Homebrew isn't ready yet

Closing in favor of https://github.com/fastred/IBAnalyzer/issues/4.
